<a href="https://colab.research.google.com/github/dh839/AI_ML-Program/blob/main/DAY_3_NUMPY_AND_FUNCTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#single dimension
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print("Array 1:", arr1)
print("Array 1 slicing", arr1[1:3])
print("Add of two arrays", arr1 + arr2)
print("Sub of two arrays", arr1 - arr2)
print("Data type of arr1", arr1.dtype)
print("Size of arr2", arr1.size)
print("Reshape of array 1", arr1.reshape(5, 1))

arr3 = np.array([20, 10, 2, 3, 4, 15, 1])
arr3.sort()
print("sort of array 3 elements", arr3)
print("Mean of array 3 is", arr3.mean())
print("Max of array 1", arr1.max())
print("max of array 3 is", arr3.max())
print("Min of array 3 is", arr3.min())

index = np.argmax(arr3)
print("Argmax of array3 is", index)

index1 = np.argmin(arr3)

Array 1: [1 2 3 4 5]
Array 1 slicing [2 3]
Add of two arrays [11 22 33 44 55]
Sub of two arrays [ -9 -18 -27 -36 -45]
Data type of arr1 int64
Size of arr2 5
Reshape of array 1 [[1]
 [2]
 [3]
 [4]
 [5]]
sort of array 3 elements [ 1  2  3  4 10 15 20]
Mean of array 3 is 7.857142857142857
Max of array 1 5
max of array 3 is 20
Min of array 3 is 1
Argmax of array3 is 6


In [ ]:
#two dimensional array
arr1 = np.array([[1, 2, 3],[4,5,6]])
arr2 = np.array([[10, 20, 30],[40,50,60]])
print("Array 1: ",arr1)
print("Array 2: ",arr2)
print("Size of arr1", arr1.size)
print("Data type of arr1",type(arr1))
print("After reshaping of arr1",arr1.reshape(1,6))
np.sort(arr1)
print("Sorting of arr1",arr1)
print("Min of array 1 is", arr1.min())
print("Max of array 1 is", arr1.max())
print("Argmin of array1 is", arr1.argmin())
print("Argmax of array1 is", arr1.argmax())
ar1=arr1+arr2
print("SUM", ar1)
product = arr1 * arr2
print("PRODUCT",product)
unique_arr1 = np.unique(arr1)
unique_arr2 = np.unique(arr2)
print("Unique in arr1:", unique_arr1)
print("Unique in arr2:", unique_arr2)
arr1_copy = arr1.copy()
arr2_copy = arr2.copy()
print("Original arr1", arr1)
print("Copied arr1_copy", arr1_copy)
arra1 = np.array([[1, 2, 3],[4,5,6],[1,2,1]])
arra2 = np.array([[1, 2, 3],[4,5,6],[1,2,1]])
arra3=np.dot(arra1,arra2)
print("PRODUCT", arra3)

Array 1:  [[1 2 3]
 [4 5 6]]
Array 2:  [[10 20 30]
 [40 50 60]]
Size of arr1 6
Data type of arr1 <class 'numpy.ndarray'>
After reshaping of arr1 [[1 2 3 4 5 6]]
Sorting of arr1 [[1 2 3]
 [4 5 6]]
Min of array 1 is 1
Max of array 1 is 6
Argmin of array1 is 0
Argmax of array1 is 5
SUM [[11 22 33]
 [44 55 66]]
PRODUCT [[ 10  40  90]
 [160 250 360]]
Unique in arr1: [1 2 3 4 5 6]
Unique in arr2: [10 20 30 40 50 60]
Original arr1 [[1 2 3]
 [4 5 6]]
Copied arr1_copy [[1 2 3]
 [4 5 6]]
PRODUCT [[12 18 18]
 [30 45 48]
 [10 14 16]]
